
version: '3.2'

#Services
services:

  #APACHE
  apache: 
    image: httpd:2.4
    links: 
      - mysql
    depends_on:
      - php
      - mysql
    container_name: apache
    restart: unless-stopped
    tty: true
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./DocumentRoot/:/var/www/html/
      - ./apache/demo.apache.conf:/usr/local/apache2/conf/demo.apache.conf
    networks: 
      - backend
      - frontend

  #MySQL SERVICE
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_ROOT_PASSWORD: passroot
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes: 
      - dbdata:/var/lib/mysql
      - ./mysql/my.cfn:/etc/mysql/my.cfn
    networks:
      - backend

  #PHP
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    volumes: 
      - ./DocumentRoot/:/var/www/html/
    networks:
      - backend

#DOCKER NETWORKS
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

#VOLUMES
volumes:
  dbdata:
    driver: local


