############
# CesarTavo
############

version: '3.2'

#----------------
# Services
#----------------
services:
  
  #----------------
  # APACHE SERVICE
  #----------------
  apache: 
    build: './apache/'
    depends_on:
      - php
      - mysql
    container_name: apache
    hostname: apache
    restart: unless-stopped
    tty: true
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./html/:/var/www/html/
    networks: 
      - backend
      - frontend

  #----------------
  # MySQL SERVICE
  #----------------
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes: 
      - dbdata:/var/lib/mysql
      - ./mysql/my.cfn:/etc/mysql/my.cfn
    networks:
      - backend

  #----------------
  # PHP SERVICE
  #----------------
  php:
    build: './php/'
    container_name: php
    hostname: php
    restart: unless-stopped
    tty: true
    volumes: 
      - ./html/:/var/www/html/
    networks:
      - backend

#----------------
# DOCKER NETWORKS
#----------------
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

#----------------
# VOLUMES
#----------------
volumes:
  dbdata:
    driver: local


